version: '3'

services:
  web:
    build: .
    command: gunicorn -b 0.0.0.0:8000 sql_translator_api:app
    volumes:
    environment:
    expose:
      - 8000

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /Users/carinayang/oai_translator/cert_for_translation_service:/etc/ssl/certs:ro
    depends_on:
      - web
